# Orderer config
orderer:
  host: localhost:7050
  useTLS: false
  timeout: 5s

discovery:
  type: local
  options:
    channels:
    - name: public
      description: public channel for all members
      chaincodes:
      - name: network
        type: golang
        version: "0.1"
        description: system discovery chaincode
        policy: "AND ('OPERATORMSP.admin')"

crypto:
  type: ecdsa
  options:
    # Possible curves: P256, P384, P512
    curve: P256
    # Possible algorithms for signature: SHA256, SHA384, SHA512
    signatureAlgorithm: SHA256
    # Possible hashing algorithms: SHA2-256, SHA2-384, SHA3-256, SHA3-384
    hash: SHA2-256

msp:
- name: OPERATORMSP
  endorsers:
  - host: 127.0.0.1:27051
    grpc:
      retry:
        max: 2
        timeout: 1s
    # timeout for peer.DeliverClient
    deliver_timeout: 6s
  - host: localhost:7051
    grpc:
      retry:
        max: 5
        timeout: 2s
- name: S7MSP
  endorsers:
  - host: localhost:17051
- name: BANKMSP
  endorsers:
  - host: localhost:37051